#!/usr/bin/env python3
"""Builds public/index.html — the ONLY thing published to GitHub Pages.

This is a deliberately reduced dashboard: sourcing/scan-results and the
manual Facebook checklist only. It never touches data/pieces.json,
data/materials.json, data/suppliers.json, data/piece_costings.json, or
research/ — those hold real supplier prices, piece costings, and buy
strategy notes and must never end up in a public repo or on a public
Pages URL. If you need a field from those files on the public page, stop
and ask first — don't just import them here.

Run after tools/build-dashboard.py, or standalone:
    python3 tools/build-public-dashboard.py
"""
import datetime
import html
import json
import os
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "docs")  # GitHub Pages only serves from repo root or /docs
SCANNER_DB = os.path.join(ROOT, "tools", "scanner", "scanner.db")


def load_keywords():
    path = os.path.join(ROOT, "tools", "scanner", "keywords.json")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def load_scan_results(limit=5000):
    if not os.path.exists(SCANNER_DB):
        return [], 0, None
    conn = sqlite3.connect(SCANNER_DB)
    conn.row_factory = sqlite3.Row
    total = conn.execute("SELECT COUNT(*) FROM lots").fetchone()[0]
    last_scan = conn.execute("SELECT MAX(last_seen) FROM lots").fetchone()[0]
    rows = conn.execute(
        """SELECT * FROM lots
           ORDER BY bad_listing_score DESC, first_seen DESC
           LIMIT ?""",
        (limit,),
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows], total, last_scan


def money(v, dash="—"):
    if v is None:
        return dash
    return "{:,.0f} kr".format(v)


def render(tpl, **kw):
    out = tpl
    for k, v in kw.items():
        out = out.replace("{" + k + "}", v)
    return out

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vedda Studio — sourcing</title>
<link rel="stylesheet" href="site/styles.css">
<link rel="stylesheet" href="dashboard.css">
</head>
<body>
<div class="page">
  <div class="nav">
    <span class="nav-brand">Vedda Studio</span>
    <span class="text-muted" style="margin-right:auto;">sourcing — public view</span>
  </div>

  <div style="padding:var(--space-6) 0;">
    <p class="text-muted">Auction scan results and the manual Facebook Marketplace checklist. Nothing else from the internal dashboard is published here — no costings, no supplier prices, no buy-strategy notes.</p>
  </div>

  <section class="section-block">
    <h4>Scan results</h4>
    <p class="text-muted">
      Auctionet, Tradera, Bukowskis, Haraldssons.
      <strong>{scan_total} lots archived</strong>, {scan_count} shown here, ranked by bad-listing score (🚩 = ≥3, worth reading first). New and loved shown; discarded is out of the way.
      Shared with everyone who opens this page. <span id="scan-last-updated" data-last-scan="{scan_last_seen_utc}"></span>
      <a href="#" id="scan-show-discarded" class="btn-link scan-discarded-link"><span id="scan-link-label">Show discarded</span> (<span id="scan-discarded-count">0</span>)</a>
    </p>
    <div class="tabnav" id="scan-source-tabs" role="tablist" style="margin-bottom:var(--space-6);"></div>
    <div class="scangrid" id="scan-grid">{scan_cards_html}</div>
    <div class="scanpager" id="scan-pager"></div>
  </section>

  <section class="section-block">
    <h4>Manual checklist — Facebook Marketplace</h4>
    <p class="text-muted">
      Can't be automated — Meta's ToS bans automated collection, with real enforcement history. Search these yourself, one at a time — click a term to copy it and mark it checked, then paste straight into Facebook's search box.
      Progress: <span id="chk-progress">0</span>/{checklist_total} checked. Saved in this browser only.
      <button id="chk-reset" type="button" class="btn btn-secondary" style="margin-left:8px; padding:6px 14px;">Reset</button>
    </p>
    <div class="chk-grid">{checklist_html}</div>
  </section>

  <footer>
    Generated by <code>tools/build-public-dashboard.py</code>. Published subset only —
    the full dashboard (costings, suppliers, pieces) is not on this site.
  </footer>
</div>

<script>
(function () {
  var el = document.getElementById('scan-last-updated');
  var lastIso = el && el.getAttribute('data-last-scan');
  if (el && lastIso) {
    var last = new Date(lastIso);
    if (!isNaN(last)) el.textContent = 'Last updated ' + last.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) + '.';
  }
})();

(function () {
  var cards = Array.prototype.slice.call(document.querySelectorAll('.scancard'));
  if (!cards.length) return;
  var showDiscardedLink = document.getElementById('scan-show-discarded');
  var discardedCountEl = document.getElementById('scan-discarded-count');
  var pagerEl = document.getElementById('scan-pager');
  var discardedVisible = false;
  var sourceFilter = 'all';
  var PAGE_SIZE = 36;
  var currentPage = 1;
  var SOURCE_LABEL = { auctionet: 'Auctionet', tradera: 'Tradera', bukowskis: 'Bukowskis', haraldssons: 'Haraldssons' };

  var SUPABASE_URL = 'https://rnquevahynifwpyynrbd.supabase.co';
  var SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJucXVldmFoeW5pZndweXlucmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk2MDQ5NDIsImV4cCI6MjEwNTE4MDk0Mn0.2xIZMYpxk-c6_xt7x8J0EkzRMWyRRRu4gy4kIEtLy1U';

  function sbHeaders() {
    return { 'apikey': SUPABASE_ANON_KEY, 'Authorization': 'Bearer ' + SUPABASE_ANON_KEY, 'Content-Type': 'application/json' };
  }

  function sbPatch(lotKey, fields) {
    return fetch(SUPABASE_URL + '/rest/v1/lots?lot_key=eq.' + encodeURIComponent(lotKey), {
      method: 'PATCH',
      headers: Object.assign(sbHeaders(), { 'Prefer': 'return=minimal' }),
      body: JSON.stringify(fields)
    }).catch(function (e) { console.warn('Supabase sync failed', e); });
  }

  function loadStates() {
    return fetch(SUPABASE_URL + '/rest/v1/lots?select=lot_key,state,discard_reason,bought_price,bought_date&state=neq.new', {
      headers: sbHeaders()
    }).then(function (r) { return r.ok ? r.json() : []; }).catch(function () { return []; });
  }

  function renderSourceTabs() {
    var tabsEl = document.getElementById('scan-source-tabs');
    if (!tabsEl) return;
    var counts = { all: cards.length };
    cards.forEach(function (card) {
      var src = card.getAttribute('data-source') || '';
      counts[src] = (counts[src] || 0) + 1;
    });
    var sources = Object.keys(SOURCE_LABEL).filter(function (s) { return counts[s]; });
    var html = '<button class="tabbtn' + (sourceFilter === 'all' ? ' is-active' : '') + '" data-source-tab="all" type="button">All (' + counts.all + ')</button>';
    sources.forEach(function (s) {
      html += '<button class="tabbtn' + (sourceFilter === s ? ' is-active' : '') + '" data-source-tab="' + s + '" type="button">' + SOURCE_LABEL[s] + ' (' + counts[s] + ')</button>';
    });
    tabsEl.innerHTML = html;
    tabsEl.querySelectorAll('[data-source-tab]').forEach(function (btn) {
      btn.addEventListener('click', function () {
        sourceFilter = btn.getAttribute('data-source-tab');
        currentPage = 1;
        applyFilters();
      });
    });
  }

  function applyFilters() {
    var discardedCount = 0;
    var eligible = [];
    cards.forEach(function (card) {
      var state = card.getAttribute('data-state') || 'new';
      var matchesSource = sourceFilter === 'all' || card.getAttribute('data-source') === sourceFilter;
      if (state === 'discarded') {
        discardedCount++;
        if (discardedVisible && matchesSource) eligible.push(card);
      } else if (matchesSource) {
        eligible.push(card);
      }
    });
    renderSourceTabs();
    if (discardedCountEl) discardedCountEl.textContent = discardedCount;

    var pageCount = Math.max(1, Math.ceil(eligible.length / PAGE_SIZE));
    if (currentPage > pageCount) currentPage = pageCount;
    var start = (currentPage - 1) * PAGE_SIZE;
    var end = start + PAGE_SIZE;

    cards.forEach(function (card) { card.hidden = true; });
    eligible.slice(start, end).forEach(function (card) { card.hidden = false; });

    renderPager(pageCount);
  }

  function renderPager(pageCount) {
    if (!pagerEl) return;
    if (pageCount <= 1) { pagerEl.innerHTML = ''; return; }
    var out = '';
    out += '<button type="button" class="btn btn-secondary scanpage-btn" data-page="' + (currentPage - 1) + '"' + (currentPage === 1 ? ' disabled' : '') + '>‹ Prev</button>';
    out += '<span class="scanpage-status">Page ' + currentPage + ' of ' + pageCount + '</span>';
    out += '<button type="button" class="btn btn-secondary scanpage-btn" data-page="' + (currentPage + 1) + '"' + (currentPage === pageCount ? ' disabled' : '') + '>Next ›</button>';
    pagerEl.innerHTML = out;
    pagerEl.querySelectorAll('.scanpage-btn').forEach(function (btn) {
      btn.addEventListener('click', function () {
        var target = parseInt(btn.getAttribute('data-page'), 10);
        if (!target || target < 1) return;
        currentPage = target;
        applyFilters();
        var gridEl = document.getElementById('scan-grid');
        if (gridEl) gridEl.scrollIntoView({ block: 'start', behavior: 'smooth' });
      });
    });
  }

  var STATE_MAP = { love: 'loved', bought: 'bought', discard: 'discarded' };
  var STATE_TAG_LABEL = { loved: 'LOVED', bought: 'BOUGHT' };

  function updateStateTag(card) {
    var state = card.getAttribute('data-state') || 'new';
    var top = card.querySelector('.scantop');
    if (!top) return;
    var existing = top.querySelector('.scan-state-tag');
    if (existing) existing.remove();
    var label = STATE_TAG_LABEL[state];
    if (label) {
      var tag = document.createElement('span');
      tag.className = 'tag tag-accent scan-state-tag';
      tag.textContent = label;
      top.appendChild(tag);
    }
  }

  cards.forEach(function (card) {
    var lotKey = card.getAttribute('data-lot-key');

    card.querySelectorAll('.scanbtn').forEach(function (btn) {
      btn.addEventListener('click', function () {
        var action = btn.getAttribute('data-action');
        var targetState = STATE_MAP[action];
        var current = card.getAttribute('data-state') || 'new';
        var next = current === targetState ? 'new' : targetState;

        var fields = { state: next };
        if (next === 'discarded') {
          var reason = window.prompt('Why discard this one? (optional — helps refine the buy filter later)', '');
          fields.discard_reason = reason || null;
        } else if (next === 'bought') {
          var price = window.prompt('Price paid (kr)?', '');
          var date = window.prompt('Purchase date (YYYY-MM-DD)?', new Date().toISOString().slice(0, 10));
          fields.bought_price = price ? parseFloat(price) : null;
          fields.bought_date = date || null;
        } else {
          fields.discard_reason = null;
        }

        card.setAttribute('data-state', next);
        updateStateTag(card);
        applyFilters();
        sbPatch(lotKey, fields);
      });
    });
  });

  var linkLabel = document.getElementById('scan-link-label');
  if (showDiscardedLink) {
    showDiscardedLink.addEventListener('click', function (e) {
      e.preventDefault();
      discardedVisible = !discardedVisible;
      if (linkLabel) linkLabel.textContent = discardedVisible ? 'Hide discarded' : 'Show discarded';
      currentPage = 1;
      applyFilters();
    });
  }

  loadStates().then(function (rows) {
    var byKey = {};
    rows.forEach(function (r) { byKey[r.lot_key] = r; });
    cards.forEach(function (card) {
      var row = byKey[card.getAttribute('data-lot-key')];
      if (row && row.state) card.setAttribute('data-state', row.state);
      updateStateTag(card);
    });
    applyFilters();
  });

  applyFilters();
})();

(function () {
  var boxes = document.querySelectorAll('.chk-row input[type="checkbox"]');
  var progressEl = document.getElementById('chk-progress');
  var resetBtn = document.getElementById('chk-reset');
  if (!boxes.length) return;

  function storeKey(term) { return 'vs-chk-' + term; }

  function updateProgress() {
    var checked = 0;
    boxes.forEach(function (b) { if (b.checked) checked++; });
    if (progressEl) progressEl.textContent = checked;
  }

  boxes.forEach(function (box) {
    var term = box.getAttribute('data-term');
    var row = box.closest('.chk-row');
    try {
      if (localStorage.getItem(storeKey(term)) === '1') {
        box.checked = true;
        row.classList.add('is-checked');
      }
    } catch (e) {}
    box.addEventListener('change', function () {
      row.classList.toggle('is-checked', box.checked);
      try { localStorage.setItem(storeKey(term), box.checked ? '1' : '0'); } catch (e) {}
      updateProgress();
    });
  });

  document.querySelectorAll('.chk-term').forEach(function (span) {
    span.addEventListener('click', function () {
      var text = span.getAttribute('data-copy');
      try { navigator.clipboard.writeText(text); } catch (e) {}
      var row = span.closest('.chk-row');
      var box = row.querySelector('input[type="checkbox"]');
      box.checked = true;
      row.classList.add('is-checked');
      try { localStorage.setItem(storeKey(box.getAttribute('data-term')), '1'); } catch (e) {}
      updateProgress();
    });
  });

  if (resetBtn) {
    resetBtn.addEventListener('click', function () {
      boxes.forEach(function (box) {
        box.checked = false;
        box.closest('.chk-row').classList.remove('is-checked');
        try { localStorage.removeItem(storeKey(box.getAttribute('data-term'))); } catch (e) {}
      });
      updateProgress();
    });
  }

  updateProgress();
})();
</script>
</body>
</html>
"""


def dedupe_variants(terms):
    seen_base = set()
    out = []
    for t in terms:
        base = t.lower().replace("-", " ").replace("ø", "o").replace("å", "a").replace("æ", "ae")
        base = "".join(c for c in base if c.isalnum() or c == " ")
        if base in seen_base:
            continue
        seen_base.add(base)
        out.append(t)
    return out


def format_scan_ends_at(value):
    if not value:
        return "—"
    try:
        if isinstance(value, str) and value.isdigit():
            value = int(value)
        if isinstance(value, (int, float)):
            dt = datetime.datetime.fromtimestamp(value)
        else:
            dt = datetime.datetime.fromisoformat(value)
        return dt.strftime("%d %b")
    except (ValueError, OSError, TypeError):
        return "—"


def parse_scan_ends_at(value):
    if not value:
        return None
    try:
        if isinstance(value, str) and value.isdigit():
            value = int(value)
        if isinstance(value, (int, float)):
            return datetime.datetime.fromtimestamp(value)
        return datetime.datetime.fromisoformat(value)
    except (ValueError, OSError, TypeError):
        return None


def scan_ends_badge(value):
    """(label, urgency_class) for the badge overlaid on the lot image —
    see tools/build-dashboard.py's twin of this function for the full
    rationale. Keep both in sync."""
    dt = parse_scan_ends_at(value)
    if not dt:
        return "—", ""
    if dt.tzinfo is not None:
        dt = dt.astimezone().replace(tzinfo=None)
    hours = (dt - datetime.datetime.now()).total_seconds() / 3600
    if hours < 0:
        return "ended", ""
    if hours < 24:
        label = f"{max(1, round(hours))}H"
    else:
        days = round(hours / 24)
        label = f"{days}D" if days < 7 else dt.strftime("%d %b")
    urgency = "urgent" if hours < 6 else "soon" if hours < 24 else ""
    return label, urgency


SCAN_SRC_LABEL = {"auctionet": "Auctionet", "tradera": "Tradera", "bukowskis": "Bukowskis", "haraldssons": "Haraldssons", "siko": "Sikö"}


def main():
    esc = html.escape
    kw = load_keywords()
    scan_lots, scan_total, scan_last_seen = load_scan_results()

    def scan_card(lot):
        lot_key = esc(f"{lot['source']}-{lot['lot_id']}")
        flag = '<span class="scanflag">🚩</span>' if (lot.get("bad_listing_score") or 0) >= 3 else ""
        img = (
            f'<img src="{esc(lot["image_url"])}" alt="" loading="lazy">'
            if lot.get("image_url")
            else ''
        )
        src = lot.get("source") or ""
        location = lot.get("location")
        location_badge = f'<span class="tag tag-accent-2">{esc(location)}</span>' if location else ""
        current_bid = lot.get("current_bid")
        price_badge = (
            f'<span class="scanprice">{money(current_bid)}</span>'
            if current_bid is not None
            else '<span class="scanprice scanprice-empty">price tbc</span>'
        )
        est_low, est_high = lot.get("estimate_low"), lot.get("estimate_high")
        if est_low is not None or est_high is not None:
            est_label = f"{money(est_low) if est_low is not None else '?'}–{money(est_high) if est_high is not None else '?'}"
            within = ""
            extra = ""
            if current_bid is not None and est_low is not None and est_high is not None and est_high > est_low:
                pct = max(0.0, min(1.0, (current_bid - est_low) / (est_high - est_low)))
                within = (
                    '<div class="estimate-range"><div class="estimate-track">'
                    f'<div class="estimate-fill" style="width:{pct * 100:.1f}%"></div>'
                    '</div></div>'
                )
                if current_bid > est_high:
                    over_pct = (current_bid - est_high) / est_high * 100
                    extra = f'<div class="scanestimate-note note-critical">{over_pct:.0f}% over high estimate</div>'
            elif current_bid is None and (est_low is not None or est_high is not None):
                extra = '<div class="scanestimate-note text-muted" style="font-style:italic;">Opening only</div>'
            estimate_html = (
                '<div class="scanrow"><span class="scanrow-label">Current bid</span>'
                '<span class="scanrow-label scanrow-label-right">Estimate</span></div>'
                f'<div class="scanrow"><span class="scanrow-value">{money(current_bid)}</span>'
                f'<span class="scanrow-value scanrow-value-right">{est_label}</span></div>'
                f'{within}{extra}'
            )
        else:
            estimate_html = ""
        ends_label, ends_urgency = scan_ends_badge(lot.get("ends_at"))
        ends_badge = (
            f'<span class="scanends-badge{(" " + ends_urgency) if ends_urgency else ""}" '
            f'title="ends {esc(format_scan_ends_at(lot.get("ends_at")))}">'
            f'⏱ ENDS {esc(ends_label)}</span>'
        )
        return (
            f'<div class="scancard" data-lot-key="{lot_key}" data-source="{esc(src)}">'
            f'<div class="fig ar-square scanimgwrap">{img}{price_badge}{ends_badge}</div>'
            '<div class="scanbody">'
            f'<div class="scantop"><span class="tag tag-outline">{esc(SCAN_SRC_LABEL.get(src, src))}</span>{flag}'
            f'{location_badge}</div>'
            f'<a class="scantitle" href="{esc(lot.get("url") or "#")}" target="_blank">{esc(lot.get("title") or "")}</a>'
            f'<div class="text-muted scanmeta">matched "{esc(lot.get("matched_keyword") or "")}"</div>'
            f'{estimate_html}'
            '<div class="scanactions">'
            f'<button class="btn btn-secondary scanbtn scanbtn-love" data-action="love" type="button">♡ Love</button>'
            f'<button class="btn btn-secondary scanbtn scanbtn-bought" data-action="bought" type="button">$ Bought</button>'
            f'<button class="btn btn-secondary scanbtn scanbtn-discard" data-action="discard" type="button">✕ Discard</button>'
            '</div>'
            '</div></div>'
        )

    scan_cards_html = "".join(scan_card(l) for l in scan_lots)
    scan_count = len(scan_lots)

    CHECKLIST_GROUPS = [
        ("Designers", dedupe_variants(kw.get("designers", []))),
        ("Models", dedupe_variants(kw.get("models", []))),
        ("Woods", ["jakaranda", "palisander", "afrormosia", "valnöt", "alm", "teak"]),
        ("Lazy-listing (the alpha terms)", kw.get("lazy_listing_terms", [])),
        ("Styles & types", kw.get("no_designer_items", [])),
    ]
    checklist_total = sum(len(items) for _, items in CHECKLIST_GROUPS)

    def checklist_group_html(label, items):
        rows = "".join(
            f'<div class="chk-row">'
            f'<input type="checkbox" data-term="{esc(t)}">'
            f'<span class="chk-term" data-copy="{esc(t)}" title="Click to copy &amp; mark checked" tabindex="0" role="button">{esc(t)}</span>'
            f'</div>'
            for t in items
        )
        return f'<div class="chk-group"><h5>{esc(label)} <span class="text-muted">({len(items)})</span></h5><div class="chk-list">{rows}</div></div>'

    checklist_html = "".join(checklist_group_html(label, items) for label, items in CHECKLIST_GROUPS)

    html_out = render(
        TEMPLATE,
        scan_total=str(scan_total),
        scan_last_seen_utc=esc((scan_last_seen or "").replace(" ", "T") + ("Z" if scan_last_seen else "")),
        scan_count=str(scan_count),
        scan_cards_html=scan_cards_html or '<p class="text-muted">No scan results yet.</p>',
        checklist_total=str(checklist_total),
        checklist_html=checklist_html,
    )

    os.makedirs(OUT_DIR, exist_ok=True)
    os.makedirs(os.path.join(OUT_DIR, "site"), exist_ok=True)
    with open(os.path.join(OUT_DIR, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(html_out)

    # Only the CSS gets copied in — not the rest of site/ (brand guide docs,
    # uploads, component reference pages aren't meant for a public site).
    import shutil
    shutil.copyfile(os.path.join(ROOT, "dashboard.css"), os.path.join(OUT_DIR, "dashboard.css"))
    shutil.copyfile(os.path.join(ROOT, "site", "styles.css"), os.path.join(OUT_DIR, "site", "styles.css"))
    # styles.css @imports the token chain — mapping-light -> semantic-branding
    # -> global-default — those have to be published too or the browser 404s/503s
    # trying to fetch them.
    os.makedirs(os.path.join(OUT_DIR, "site", "tokens"), exist_ok=True)
    for token_file in ("mapping-light.css", "semantic-branding-default.css", "global-default.css"):
        shutil.copyfile(
            os.path.join(ROOT, "site", "tokens", token_file),
            os.path.join(OUT_DIR, "site", "tokens", token_file),
        )

    print(f"wrote {os.path.join(OUT_DIR, 'index.html')}")
    print(f"  scan lots: {scan_count} shown / {scan_total} archived · checklist terms: {checklist_total}")


if __name__ == "__main__":
    main()
