#!/usr/bin/env python3
"""Builds public/index.html — the ONLY thing published to GitHub Pages.

This is a deliberately reduced dashboard: sourcing/scan-results and the
manual Facebook checklist only. It never touches data/pieces.json,
data/materials.json, data/suppliers.json, data/piece_costings.json, or
research/ — those hold real supplier prices, piece costings, and buy
strategy notes and must never end up in a public repo or on a public
Pages URL. If you need a field from those files on the public page, stop
and ask first — don't just import them here.

Run after tools/build-dashboard.py, or standalone:
    python3 tools/build-public-dashboard.py
"""
import datetime
import html
import json
import os
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "docs")  # GitHub Pages only serves from repo root or /docs
SCANNER_DB = os.path.join(ROOT, "tools", "scanner", "scanner.db")


def load_keywords():
    path = os.path.join(ROOT, "tools", "scanner", "keywords.json")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def load_scan_results(limit=2000):
    if not os.path.exists(SCANNER_DB):
        return [], 0
    conn = sqlite3.connect(SCANNER_DB)
    conn.row_factory = sqlite3.Row
    total = conn.execute("SELECT COUNT(*) FROM lots").fetchone()[0]
    rows = conn.execute(
        """SELECT * FROM lots
           ORDER BY bad_listing_score DESC, first_seen DESC
           LIMIT ?""",
        (limit,),
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows], total


def render(tpl, **kw):
    out = tpl
    for k, v in kw.items():
        out = out.replace("{" + k + "}", v)
    return out

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vedda Studio — sourcing</title>
<link rel="stylesheet" href="site/styles.css">
<link rel="stylesheet" href="dashboard.css">
</head>
<body>
<div class="page" style="max-width:1100px; margin:0 auto; padding-left:var(--space-6); padding-right:var(--space-6);">

  <div class="hero-block">
    <span class="kicker">Vedda Studio</span>
    <h1 class="hero-value" style="font-size:32px;">Sourcing</h1>
    <p class="text-muted">Auction scan results and the manual Facebook Marketplace checklist. Nothing else from the internal dashboard is published here — no costings, no supplier prices, no buy-strategy notes.</p>
  </div>

  <section class="section-block">
    <h4>Scan results</h4>
    <p class="text-muted">
      Auctionet, Tradera, Bukowskis, Haraldssons.
      <strong>{scan_total} lots archived</strong>, {scan_count} shown here, ranked by bad-listing score (🚩 = ≥3, worth reading first). New and loved shown; discarded is out of the way.
      Saved in this browser only.
      <a href="#" id="scan-show-discarded" class="btn-link scan-discarded-link"><span id="scan-link-label">Show discarded</span> (<span id="scan-discarded-count">0</span>)</a>
    </p>
    <div class="scangrid" id="scan-grid">{scan_cards_html}</div>
    <div class="scanpager" id="scan-pager"></div>
  </section>

  <section class="section-block">
    <h4>Manual checklist — Facebook Marketplace</h4>
    <p class="text-muted">
      Can't be automated — Meta's ToS bans automated collection, with real enforcement history. Search these yourself, one at a time — click a term to copy it and mark it checked, then paste straight into Facebook's search box.
      Progress: <span id="chk-progress">0</span>/{checklist_total} checked. Saved in this browser only.
      <button id="chk-reset" type="button" class="btn btn-secondary" style="margin-left:8px; padding:6px 14px;">Reset</button>
    </p>
    <div class="chk-grid">{checklist_html}</div>
  </section>

  <footer>
    Generated by <code>tools/build-public-dashboard.py</code>. Published subset only —
    the full dashboard (costings, suppliers, pieces) is not on this site.
  </footer>
</div>

<script>
(function () {{
  var cards = Array.prototype.slice.call(document.querySelectorAll('.scancard'));
  if (!cards.length) return;
  var showDiscardedLink = document.getElementById('scan-show-discarded');
  var discardedCountEl = document.getElementById('scan-discarded-count');
  var pagerEl = document.getElementById('scan-pager');
  var discardedVisible = false;
  var PAGE_SIZE = 36;
  var currentPage = 1;

  function storeKey(lotKey) {{ return 'vs-scan-' + lotKey; }}

  function applyFilters() {{
    var discardedCount = 0;
    var eligible = [];
    cards.forEach(function (card) {{
      var state = card.getAttribute('data-state') || 'new';
      if (state === 'discarded') {{
        discardedCount++;
        if (discardedVisible) eligible.push(card);
      }} else {{
        eligible.push(card);
      }}
    }});
    if (discardedCountEl) discardedCountEl.textContent = discardedCount;

    var pageCount = Math.max(1, Math.ceil(eligible.length / PAGE_SIZE));
    if (currentPage > pageCount) currentPage = pageCount;
    var start = (currentPage - 1) * PAGE_SIZE;
    var end = start + PAGE_SIZE;

    cards.forEach(function (card) {{ card.hidden = true; }});
    eligible.slice(start, end).forEach(function (card) {{ card.hidden = false; }});

    renderPager(pageCount);
  }}

  function renderPager(pageCount) {{
    if (!pagerEl) return;
    if (pageCount <= 1) {{ pagerEl.innerHTML = ''; return; }}
    var out = '';
    out += '<button type="button" class="btn btn-secondary scanpage-btn" data-page="' + (currentPage - 1) + '"' + (currentPage === 1 ? ' disabled' : '') + '>‹ Prev</button>';
    out += '<span class="scanpage-status">Page ' + currentPage + ' of ' + pageCount + '</span>';
    out += '<button type="button" class="btn btn-secondary scanpage-btn" data-page="' + (currentPage + 1) + '"' + (currentPage === pageCount ? ' disabled' : '') + '>Next ›</button>';
    pagerEl.innerHTML = out;
    pagerEl.querySelectorAll('.scanpage-btn').forEach(function (btn) {{
      btn.addEventListener('click', function () {{
        var target = parseInt(btn.getAttribute('data-page'), 10);
        if (!target || target < 1) return;
        currentPage = target;
        applyFilters();
        pagerEl.scrollIntoView({{ block: 'nearest' }});
      }});
    }});
  }}

  cards.forEach(function (card) {{
    var lotKey = card.getAttribute('data-lot-key');
    var saved = null;
    try {{ saved = localStorage.getItem(storeKey(lotKey)); }} catch (e) {{}}
    if (saved) card.setAttribute('data-state', saved);

    card.querySelectorAll('.scanbtn').forEach(function (btn) {{
      btn.addEventListener('click', function () {{
        var action = btn.getAttribute('data-action');
        var current = card.getAttribute('data-state') || 'new';
        var next = current === action + 'd' || current === action ? 'new' : (action === 'love' ? 'loved' : 'discarded');
        card.setAttribute('data-state', next);
        try {{
          if (next === 'new') localStorage.removeItem(storeKey(lotKey));
          else localStorage.setItem(storeKey(lotKey), next);
        }} catch (e) {{}}
        applyFilters();
      }});
    }});
  }});

  var linkLabel = document.getElementById('scan-link-label');
  if (showDiscardedLink) {{
    showDiscardedLink.addEventListener('click', function (e) {{
      e.preventDefault();
      discardedVisible = !discardedVisible;
      if (linkLabel) linkLabel.textContent = discardedVisible ? 'Hide discarded' : 'Show discarded';
      currentPage = 1;
      applyFilters();
    }});
  }}

  applyFilters();
}})();

(function () {{
  var boxes = document.querySelectorAll('.chk-row input[type="checkbox"]');
  var progressEl = document.getElementById('chk-progress');
  var resetBtn = document.getElementById('chk-reset');
  if (!boxes.length) return;

  function storeKey(term) {{ return 'vs-chk-' + term; }}

  function updateProgress() {{
    var checked = 0;
    boxes.forEach(function (b) {{ if (b.checked) checked++; }});
    if (progressEl) progressEl.textContent = checked;
  }}

  boxes.forEach(function (box) {{
    var term = box.getAttribute('data-term');
    var row = box.closest('.chk-row');
    try {{
      if (localStorage.getItem(storeKey(term)) === '1') {{
        box.checked = true;
        row.classList.add('is-checked');
      }}
    }} catch (e) {{}}
    box.addEventListener('change', function () {{
      row.classList.toggle('is-checked', box.checked);
      try {{ localStorage.setItem(storeKey(term), box.checked ? '1' : '0'); }} catch (e) {{}}
      updateProgress();
    }});
  }});

  document.querySelectorAll('.chk-term').forEach(function (span) {{
    span.addEventListener('click', function () {{
      var text = span.getAttribute('data-copy');
      try {{ navigator.clipboard.writeText(text); }} catch (e) {{}}
      var row = span.closest('.chk-row');
      var box = row.querySelector('input[type="checkbox"]');
      box.checked = true;
      row.classList.add('is-checked');
      try {{ localStorage.setItem(storeKey(box.getAttribute('data-term')), '1'); }} catch (e) {{}}
      updateProgress();
    }});
  }});

  if (resetBtn) {{
    resetBtn.addEventListener('click', function () {{
      boxes.forEach(function (box) {{
        box.checked = false;
        box.closest('.chk-row').classList.remove('is-checked');
        try {{ localStorage.removeItem(storeKey(box.getAttribute('data-term'))); }} catch (e) {{}}
      }});
      updateProgress();
    }});
  }}

  updateProgress();
}})();
</script>
</body>
</html>
"""


def dedupe_variants(terms):
    seen_base = set()
    out = []
    for t in terms:
        base = t.lower().replace("-", " ").replace("ø", "o").replace("å", "a").replace("æ", "ae")
        base = "".join(c for c in base if c.isalnum() or c == " ")
        if base in seen_base:
            continue
        seen_base.add(base)
        out.append(t)
    return out


def format_scan_ends_at(value):
    if not value:
        return "—"
    try:
        if isinstance(value, str) and value.isdigit():
            value = int(value)
        if isinstance(value, (int, float)):
            dt = datetime.datetime.fromtimestamp(value)
        else:
            dt = datetime.datetime.fromisoformat(value)
        return dt.strftime("%d %b")
    except (ValueError, OSError, TypeError):
        return "—"


SCAN_SRC_LABEL = {"auctionet": "Auctionet", "tradera": "Tradera", "bukowskis": "Bukowskis", "haraldssons": "Haraldssons"}


def main():
    esc = html.escape
    kw = load_keywords()
    scan_lots, scan_total = load_scan_results()

    def scan_card(lot):
        price = lot.get("current_bid")
        price_html = (
            f'<div class="scanprice">{int(price):,} kr</div>'.replace(",", " ")
            if price
            else '<div class="scanprice scanprice-empty">no bid</div>'
        )
        flag = '<span class="scanflag">🚩</span>' if (lot.get("bad_listing_score") or 0) >= 3 else ""
        img = lot.get("image_url")
        img_html = f'<img src="{esc(img)}" alt="" loading="lazy">' if img else ""
        lot_key = f'{lot.get("source")}-{lot.get("lot_id")}'
        return (
            f'<div class="card scancard" data-state="new" data-lot-key="{esc(lot_key)}">'
            f'<div class="scanimgwrap fig ar-4-3">{img_html}{price_html}</div>'
            '<div class="scanbody">'
            '<div class="scantop">'
            f'{flag}<span class="tag">{esc(SCAN_SRC_LABEL.get(lot.get("source"), lot.get("source") or ""))}</span>'
            f'<span class="scanends text-muted">ends {esc(format_scan_ends_at(lot.get("ends_at")))}</span>'
            '</div>'
            f'<a class="scantitle" href="{esc(lot.get("url") or "#")}" target="_blank" rel="noopener">{esc(lot.get("title") or "Untitled lot")}</a>'
            f'<div class="text-muted scanmeta">matched "{esc(lot.get("matched_keyword") or "")}"</div>'
            '<div class="scanactions">'
            '<button class="btn btn-secondary scanbtn scanbtn-love" data-action="love" type="button">♡ Love</button>'
            '<button class="btn btn-secondary scanbtn scanbtn-discard" data-action="discard" type="button">✕ Discard</button>'
            '</div>'
            '</div></div>'
        )

    scan_cards_html = "".join(scan_card(l) for l in scan_lots)
    scan_count = len(scan_lots)

    CHECKLIST_GROUPS = [
        ("Designers", dedupe_variants(kw.get("designers", []))),
        ("Models", dedupe_variants(kw.get("models", []))),
        ("Woods", ["jakaranda", "palisander", "afrormosia", "valnöt", "alm", "teak"]),
        ("Lazy-listing (the alpha terms)", kw.get("lazy_listing_terms", [])),
        ("Styles & types", kw.get("no_designer_items", [])),
    ]
    checklist_total = sum(len(items) for _, items in CHECKLIST_GROUPS)

    def checklist_group_html(label, items):
        rows = "".join(
            f'<div class="chk-row">'
            f'<input type="checkbox" data-term="{esc(t)}">'
            f'<span class="chk-term" data-copy="{esc(t)}" title="Click to copy &amp; mark checked" tabindex="0" role="button">{esc(t)}</span>'
            f'</div>'
            for t in items
        )
        return f'<div class="chk-group"><h5>{esc(label)} <span class="text-muted">({len(items)})</span></h5><div class="chk-list">{rows}</div></div>'

    checklist_html = "".join(checklist_group_html(label, items) for label, items in CHECKLIST_GROUPS)

    html_out = render(
        TEMPLATE,
        scan_total=str(scan_total),
        scan_count=str(scan_count),
        scan_cards_html=scan_cards_html or '<p class="text-muted">No scan results yet.</p>',
        checklist_total=str(checklist_total),
        checklist_html=checklist_html,
    )

    os.makedirs(OUT_DIR, exist_ok=True)
    os.makedirs(os.path.join(OUT_DIR, "site"), exist_ok=True)
    with open(os.path.join(OUT_DIR, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(html_out)

    # Only the CSS gets copied in — not the rest of site/ (brand guide docs,
    # uploads, component reference pages aren't meant for a public site).
    import shutil
    shutil.copyfile(os.path.join(ROOT, "dashboard.css"), os.path.join(OUT_DIR, "dashboard.css"))
    shutil.copyfile(os.path.join(ROOT, "site", "styles.css"), os.path.join(OUT_DIR, "site", "styles.css"))

    print(f"wrote {os.path.join(OUT_DIR, 'index.html')}")
    print(f"  scan lots: {scan_count} shown / {scan_total} archived · checklist terms: {checklist_total}")


if __name__ == "__main__":
    main()
